Vagrant.configure(2) do |config|
    config.vm.define "web" do |web|
        web.vm.box = "ubuntu/trusty32"
        web.vm.network "private_network", ip: "10.10.10.7"
    end

    config.vm.define "db" do |db|
        db.vm.box = "ubuntu/trusty32"
        db.vm.network "private_network", ip: "10.10.10.8"
    end
end