Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/trusty32"
    config.vm.network "private_network", ip: "10.10.10.6"
    config.vm.synced_folder "D:/virtual/laravel", "/var/www/laravel"
end